name: life-backend-test
services:
  caddy-test:
    image: caddy:2
    ports:
      - "8443:8443"
    volumes:
      - ./Caddyfile-testing:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - life-net-test

  life-api-test:
    image: ghcr.io/smorris76/life-backend:testing
    env_file:
      - /home/shawn/.local/life_backend/test.env
    volumes:
      - /home/shawn/.local/life_backend/test-data:/repo
    networks:
      - life-net-test

volumes:
  caddy_data:
  caddy_config:

networks:
  life-net-test:
    driver: bridge
