version: "3.7"

services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - life-net

  life-api:
    image: life-backend:testing
    build:
      context: ../life_backend
    env_file:
      - /home/shawn/.life-data.env
    volumes:
      - /home/shawn/life-data:/repo
    networks:
      - life-net

volumes:
  caddy_data:
  caddy_config:

networks:
  life-net:
    driver: bridge
