name: life-backend

services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - life-net

  life-api:
    image: ghcr.io/smorris76/life-backend:latest
    env_file:
      - /home/shawn/.local/life_backend/prod.env
    volumes:
      - /home/shawn/.local/life_backend/prod-data:/repo
      - /home/shawn/.local/life_backend/life_html_deploy:/root/.ssh/id_deploy:ro
    networks:
      - life-net

volumes:
  caddy_data:
  caddy_config:

networks:
  life-net:
    driver: bridge
